#!/bin/bash -e

t=166;

dat=$1
while [ $dat -lt $t ];
do
g=$(echo "scale=5; ($dat)/$t" | bc)

if [ $g -eq 0 ] 
then
g=00000
fi

./pyt $dat $g
dat=$((dat+1))
done

for i in *.png; do j=`echo $i | sed 's/-./-/'`; mv $i $j; done
